language: python
python:
  - 3.6
  - 3.5
  - 3.7
env:
  - TORTOISE_TEST_DB="sqlite:///tmp/test-{}.sqlite"
  - TORTOISE_TEST_DB="postgres://postgres:@127.0.0.1:5432/test_{}"
  - TORTOISE_TEST_DB="mysql://root:@127.0.0.1:3306/test_{}"
  - TORTOISE_TEST_DB="postgres://postgres:@127.0.0.1:5432/test_{}" TORTOISE_TEST_POOL=1
  - TORTOISE_TEST_DB="mysql://root:@127.0.0.1:3306/test_{}" TORTOISE_TEST_POOL=1
dist: xenial
sudo: required
addons:
  postgresql: "9.4"
services:
  - postgresql
  - mysql
cache: pip
install:
  - pip install -r requirements-dev.txt
script:
  - make ci
after_success:
  - coveralls
